output "environment_resource_group" {
  description = "The resource group names of each environment"
  value       = azurerm_resource_group.rg
}

output "backend_id" {
  description = "Unique ID used to name resources in this module"
  value       = random_string.backend_id.result
}

output "key_vault" {
  description = "Key Vault(s) provisioned by this module"
  value       = azurerm_key_vault.backend
}

output "service_principal" {
  description = "Service principal(s) generated by this module"
  value       = module.service-principal
}

